server:
  port: 10081
spring:
  application:
    name: campus-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10080/eureka
zuul:
  prefix: /api #路由前缀
  routes:
    campus-service: /campus/**
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:5000 #熔断超时时长 5000ms
ribbon:
  ConnectTimeout: 1000 #ribbon 连接超时时长
  ReadTimeout: 3500 #读取超时时长
  MaxAutoRetries: 0 #当前服务重试次数
  MaxAutoRetriesNextServer: 0 #切换服务重试次数