server:
  port: 10080
spring:
  application:
    name: campus-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10080/eureka
    register-with-eureka: false
    fetch-registry: false